// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polifood.DAO;

#nullable disable

namespace Polifood.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317173403_migracionesConSemilla")]
    partial class migracionesConSemilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            ConcurrencyStamp = "a1a1a1a1-1111-1111-1111-111111111111",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            ConcurrencyStamp = "b2b2b2b2-2222-2222-2222-222222222222",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            ConcurrencyStamp = "c3c3c3c3-3333-3333-3333-333333333333",
                            Name = "Vendor",
                            NormalizedName = "VENDOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Polifood.Models.Admin", b =>
                {
                    b.Property<Guid>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.Property<string>("name_admin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Polifood.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Polifood.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            status = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            status = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            status = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            status = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            status = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            status = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            status = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            status = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            status = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            status = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            status = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            status = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000020"),
                            status = 3
                        });
                });

            modelBuilder.Entity("Polifood.Models.OrderItem", b =>
                {
                    b.Property<Guid>("orderItem_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.Property<Guid>("product_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("orderItem_id");

                    b.HasIndex("OrderId");

                    b.HasIndex("product_id");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000001"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000001"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000002"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000001"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000003"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000002"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000004"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000002"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000005"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000003"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000006"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000003"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000007"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000004"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000008"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000004"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000009"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000005"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000010"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000005"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000011"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000006"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000012"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000006"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000013"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000007"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000014"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000007"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000015"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000008"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000016"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000008"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000017"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000009"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000018"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000009"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000019"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000010"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000020"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000010"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000021"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000011"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000022"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000011"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000023"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000012"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000024"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000012"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000025"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000013"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000026"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000013"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000027"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000014"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000028"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000014"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000029"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000015"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000030"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000015"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000031"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000016"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000032"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000016"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000033"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000017"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000034"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000017"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000035"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000018"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000036"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000018"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000037"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000019"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000038"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000019"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000039"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000020"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            orderItem_id = new Guid("40000000-0000-0000-0000-000000000040"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000020"),
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Polifood.Models.Product", b =>
                {
                    b.Property<Guid>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.Property<bool>("is_available")
                        .HasColumnType("bit");

                    b.Property<int>("prepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("product_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("product_price")
                        .HasColumnType("int");

                    b.HasKey("product_id");

                    b.HasIndex("CartId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000001"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 15,
                            product_description = "Hamburguesa con carne, queso y vegetales",
                            product_image = "burger1.jpg",
                            product_name = "Hamburguesa Clásica",
                            product_price = 5000
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000002"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 20,
                            product_description = "Pizza individual de queso y pepperoni",
                            product_image = "pizza1.jpg",
                            product_name = "Pizza Personal",
                            product_price = 4000
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000003"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 10,
                            product_description = "Pan con salchicha, papitas y salsas",
                            product_image = "hotdog.jpg",
                            product_name = "Perro Caliente",
                            product_price = 3500
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000004"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 12,
                            product_description = "Tacos de carne con vegetales",
                            product_image = "tacos.jpg",
                            product_name = "Tacos",
                            product_price = 4200
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000005"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 14,
                            product_description = "Burrito de pollo y arroz",
                            product_image = "burrito.jpg",
                            product_name = "Burrito",
                            product_price = 4700
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000006"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 8,
                            product_description = "Nachos con queso y carne",
                            product_image = "nachos.jpg",
                            product_name = "Nachos",
                            product_price = 3900
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000007"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 9,
                            product_description = "Ensalada fresca con pollo",
                            product_image = "salad.jpg",
                            product_name = "Ensalada César",
                            product_price = 4500
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000008"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 7,
                            product_description = "Jamón, queso y vegetales",
                            product_image = "sandwich.jpg",
                            product_name = "Sándwich Mixto",
                            product_price = 3200
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000009"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 6,
                            product_description = "Empanadas rellenas de carne",
                            product_image = "empanadas.jpg",
                            product_name = "Empanadas",
                            product_price = 2500
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000010"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 11,
                            product_description = "Arepa con pollo y queso",
                            product_image = "arepa.jpg",
                            product_name = "Arepa Rellena",
                            product_price = 3800
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000011"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 18,
                            product_description = "Lasaña personal de carne",
                            product_image = "lasagna.jpg",
                            product_name = "Lasaña",
                            product_price = 5200
                        },
                        new
                        {
                            product_id = new Guid("20000000-0000-0000-0000-000000000012"),
                            is_active = 1,
                            is_available = true,
                            prepTimeMinutes = 5,
                            product_description = "Postre de chocolate",
                            product_image = "brownie.jpg",
                            product_name = "Brownie",
                            product_price = 2000
                        });
                });

            modelBuilder.Entity("Polifood.Models.Store", b =>
                {
                    b.Property<Guid>("store_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.Property<Guid?>("productId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("product_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("store_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("store_id");

                    b.HasIndex("productId");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            store_id = new Guid("10000000-0000-0000-0000-000000000001"),
                            categories = "Fast Food",
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000001"),
                            store_name = "Polifood Central"
                        },
                        new
                        {
                            store_id = new Guid("10000000-0000-0000-0000-000000000002"),
                            categories = "Snacks",
                            is_active = 1,
                            product_id = new Guid("20000000-0000-0000-0000-000000000007"),
                            store_name = "Polifood Express"
                        });
                });

            modelBuilder.Entity("Polifood.Models.Student", b =>
                {
                    b.Property<Guid>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.Property<string>("student_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Polifood.Models.Vendor", b =>
                {
                    b.Property<Guid>("vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("is_active")
                        .HasColumnType("int");

                    b.Property<Guid?>("store_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("vendor_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vendor_id");

                    b.HasIndex("IdentityUserId");

                    b.HasIndex("store_id");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Polifood.Models.Admin", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Polifood.Models.OrderItem", b =>
                {
                    b.HasOne("Polifood.Models.Order", "Order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polifood.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Polifood.Models.Product", b =>
                {
                    b.HasOne("Polifood.Models.Cart", null)
                        .WithMany("products")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("Polifood.Models.Store", b =>
                {
                    b.HasOne("Polifood.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Polifood.Models.Student", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Polifood.Models.Vendor", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polifood.Models.Store", "store")
                        .WithMany()
                        .HasForeignKey("store_id");

                    b.Navigation("IdentityUser");

                    b.Navigation("store");
                });

            modelBuilder.Entity("Polifood.Models.Cart", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Polifood.Models.Order", b =>
                {
                    b.Navigation("orderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
